"""added tasklists

Revision ID: 41f3075d0cf1
Revises: d2455a9579c1
Create Date: 2024-04-15 22:53:50.773425

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "41f3075d0cf1"
down_revision = "d2455a9579c1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "completed_tasks", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "pending_tasks", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "pending_tasks")
    op.drop_column("users", "completed_tasks")
    # ### end Alembic commands ###
