"""Убраны name, surname, email, добавлен username

Revision ID: 607a73e24168
Revises: e91c8599bdcd
Create Date: 2024-05-07 10:47:16.647323

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "607a73e24168"
down_revision = "e91c8599bdcd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(), nullable=False))
    op.drop_column("users", "surname")
    op.drop_column("users", "email")
    op.drop_column("users", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "users", sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "users", sa.Column("surname", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column("users", "username")
    # ### end Alembic commands ###
