"""hash_password added

Revision ID: d2455a9579c1
Revises: 705b8f40b80b
Create Date: 2024-04-14 18:56:30.212252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2455a9579c1'
down_revision = '705b8f40b80b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
