"""added tasklists with array again

Revision ID: e91c8599bdcd
Revises: 5cb14e0b03d2
Create Date: 2024-04-16 01:43:51.478258

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e91c8599bdcd"
down_revision = "5cb14e0b03d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("completed_tasks", postgresql.ARRAY(sa.String()), nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("pending_tasks", postgresql.ARRAY(sa.String()), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "pending_tasks")
    op.drop_column("users", "completed_tasks")
    # ### end Alembic commands ###
